# Generated by Django 5.2.17 on 2026-10-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_seed_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=180)),
                ('city', models.CharField(max_length=80)),
                ('region', models.CharField(default='OR', max_length=40)),
                ('postal_code', models.CharField(max_length=12)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('hours', models.CharField(default='Mon-Fri 7:30 am-6 pm · Sat 8 am-3 pm', max_length=140)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
