# Generated by Django 5.2.17 on 2026-10-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0007_booking_final_price_garagelocation_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='invoice_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_ready_for_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
