# Generated by Django 5.2.17 on 2026-10-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0008_booking_invoice_ready_booking_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_pending_verification',
            field=models.BooleanField(default=False),
        ),
    ]
